Yc 18
LLIHC/youtube-clone pull request #11
Opened 2022-01-28 08:23 UTC by LEEMINJOO

https://user-images.githubusercontent.com/42792260/151512196-72eaa333-c87e-4f60-8409-fae223261915.mov

2022-01-30 05:36 UTC, kynk94 requested changes
로그인 후 로그아웃 후 로그인을 하면 2가지 동작방식이 있는 것 같은데요

1. 구글 로그인 api 페이지로 이동되며 OAuth 2.0 규칙을 준수하고 있지 않다고 Bad Request 400 오류가 안내됩니다.
https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling
2. 아무런 표시없이 자동으로 로그인했던 계정으로 로그인 됩니다.

추후 react-google-login 라이브러리에 관련 이슈가 있는지 확인해보면 좋을 것 같습니다.
혹시

2022-01-30 05:36 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +    console.log(error);
console.log는 디버깅할때만 쓰는 것으로 검사도구에 의해 warning이 발생합니다.
만약 필수적 안내가 필요하다면, index.tsx가 있는 최상단 폴더에 logger를 만들어주시고
아래 코드를 작성하시고 import하여 사용해주시면 됩니다
```js
const logger = console
export default logger
```

만약 파일로 기록해야하는 로그라면, 다른 로그 라이브러리를 사용하는 것도 좋은 방법입니다

2022-01-30 05:36 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +function GoogleLoginComponent() {
결과적으로 return component는 button의 하위 객체입니다.
또, Youtube는 google login만을 지원하기에 google을 명시하지는 않아도 좋아보입니다.
(위의 2개 component는 google login의 기능이기에 명시하는 것이 좋겠지요)

그러니까 LoginButton으로 바꾼다면 더 직관적으로 코드를 읽을 수 있을 것 같아요

2022-01-30 05:36 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +function GoogleLoginBtn() {
가능한 한 축약어는 피해주세요!
`GoogleLoginButton`
`GoogleLogoutButton`

2022-01-30 05:36 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +const clientId = '986704124267-8p8q17fs47f0htp7s686suvu21rmdmf2.apps.googleusercontent.com';
이런 중요사항은 frontend에서 공개되면 공격에 취약해집니다.
때문에 .env파일을 사용하는 방향으로 바꿔주시는게 필요한데, 이건 현재 issue를 merge한 이후 다른 issue로 분리해서 작업해주시면 될것같습니다

2022-01-30 05:36 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +  const onLogoutSuccess = () => {
화살표 함수는 useCallback으로 감싸주세요
위의 async도 useCallback 내에서 정상으로 동작하는 것 같네요

2022-02-02 04:14 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +    console.log(error);
에러 로깅 방법 정의를 먼저하고 결정하면 좋을 것 같습니다.
에러 로깅 외에 로그인 실패시 실제 유튜브 작동방식 확인 후 추가 수정하면 좋을 것 같은데 어떻게 생각하시나요?

2022-02-02 04:18 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +function GoogleLoginComponent() {
* 로그인 방식이 구글만 있어 특별히 명시하지 않아도 되는 부분 동의합니다. 이름 수정하겠습니다 !
* 상태 변수에 따라 로그인 버튼과 로그아웃 버튼을 전택해서 리턴하는데 로그인 버튼으로 명시하는게 어색하다고 생각했습니다. 그래도 컴포넌트의 이름이 버튼으로 되야하는 게 맞는 것 같네요. 컴포넌트 이름은 다른 레퍼런스 확인 후 수정하겠습니다.

2022-02-02 04:25 UTC, LEEMINJOO commented
@kynk94 네, 재로그인시 문제가 있는 부분은 인지하고 있었습니다. 

1번 처럼 400 에러가 나는 상황이 일정하기 않아 추가 디버깅을 하지는 못했는데요. 
구글 콘솔에서 api를 허용하는 url을 따로 설정해줘야하는데 가끔 캐시되거나 중간에 다른 url을 거치면서 400에러가 나는 것 같습니다. 2번 상황도 캐시랑 연결되는 것 같은데, 조금 더 찾아서 다시 코멘트 드리겠습니다.

2022-02-02 06:13 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +    console.log(error);
네 좋습니다! 우선은 console.log로 사용해주세요.
Jira에 error logging 이슈 추가해두겠습니다.

2022-02-02 06:17 UTC, kynk94 commented
Cache는 아직 저희가 다루지 않고 있으니 복잡한 경우 `재로그인 기능 수정` 으로 이슈를 하나 남겨주시고 마무리해주셔도 좋습니다!

2022-02-03 12:56 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +function GoogleLoginComponent() {
추가 컴포넌트 없이 header에서 로그인 상태 확인 후 버튼 리턴하도록 변경했습니다

2022-02-03 12:57 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +const clientId = '986704124267-8p8q17fs47f0htp7s686suvu21rmdmf2.apps.googleusercontent.com';
env 파일로 변경했습니다. 협업자간 env 파일 관리는 어떻게 하는게 좋을까요?

2022-02-03 12:58 UTC, LEEMINJOO commented
@kynk94 로그인시 redirectUrl을 href에서 origin으로 변경해 재로그인 이슈 해결했습니다

2022-02-06 06:05 UTC, kynk94 approved these changes

2022-02-12 02:29 UTC, ecpark4545 commented on frontend/src/components/google-login.tsx
> +const clientId = '986704124267-8p8q17fs47f0htp7s686suvu21rmdmf2.apps.googleusercontent.com';
@kynk94 @LEEMINJOO 
타 repo안에 .secret folder로 관리하면 어떨까요?
정책은 한번 세워야할거 같습니다

2022-02-12 02:30 UTC, ecpark4545 commented
수고하셨습니다

2022-02-12 02:31 UTC, ecpark4545 approved these changes

2022-02-12 02:32 UTC, kynk94 approved these changes

2022-02-12 03:56 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +const clientId = '986704124267-8p8q17fs47f0htp7s686suvu21rmdmf2.apps.googleusercontent.com';
@ecpark4545 지난주에 youtube-env private repo를 서브모듈로 사용하자고 이야기했습니다. 참고부탁드립니다

2022-02-12 03:56 UTC, merged