add: rough Drawer
LLIHC/youtube-clone pull request #12
Opened 2022-01-30 05:04 UTC by ecpark4545

- 코드 쪼개는 작업은 하지 못했습니다.
- 커멘트 주시면 반영하도록 하겠습니다.
- 민족 대명절 설날에 다들 수고하십니다.

https://user-images.githubusercontent.com/64114323/151687386-53dbe0b4-0f2f-40de-b831-9686cfeb6082.mov

2022-02-06 13:16 UTC, kynk94 requested changes
drawer를 분리만 해도 훨씬 깔끔해질 것 같아요
아직 theme이 구현이 안되어있어 어려웠을텐데 prop을 통해 구현 하시느라 고생많으셨습니다!

2022-02-06 13:16 UTC, kynk94 commented on frontend/src/components/header.tsx
> +}, ({ drawerOpened }: StyledDrawerProps)=> ({
emotion styled에 Prop을 전달할 때에는 변수명(ex. drawerOpened) 에서 대문자가 있을 때, 오류를 발생시킵니다.
이 오류는 컴파일러에서 발생하지는 않아 아무 문제없이 동작하지만, F12를 통해 Console을 확인하시면 react가 대문자를 받지 않는다 라는 오류가 나타납니다.

때문에 여기서는 isOpen 대신 opened(다른 예로 open은 drawer의 기본 prop일텐데 적용 가능할 수도 있습니다. 기본 prop으로 표현이 가능하다면 best겠지만 아직 저도 기본 prop을 styled에 써 본적은 없어서 실험 부탁드립니다!) 등 다른 명명법을 생각해주시면 좋을 것 같습니다.

2022-02-06 13:16 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  }),
혹시 아래 1안 2안 중 동작하는 것이 있을까요? 3항연산자를 사용한 것입니다.
가능하다면 1안이 동작하면 좋을 것 같아요

```suggestion
    width: drawerOpened ? 60 : 120,
    '& .MuiDrawer-paper': { width: drawerOpened ? 60 : 120 },
```

```suggestion
  ...(drawerOpened ? {
    width: 60,
    '& .MuiDrawer-paper': { width: 60 },
  } : {
    width: 120,
    '& .MuiDrawer-paper': { width: 120 },
  }),

```

2022-02-12 02:34 UTC, ecpark4545 commented
@kynk94 코멘트 감사합니다.
수정하도록 하겠습니다.

2022-02-12 03:42 UTC, kynk94 commented
다시 고민해보았는데 open 관련을 전부 expand로 바꾸는게 더 좋을 것 같아요
이미 열려있는 것이고 확장하는 개념이니까요 (게다가 기본적으로 연다는 행위와 중복되어 헷갈릴 수 있기에)

또 영상 재생 페이지에서는 아예 닫혀있다가 누르면 열리는거니까 expand(isExpand 등)가 좋을것같습니다.

2022-02-12 03:45 UTC, ecpark4545 commented
@kynk94 
> 다시 고민해보았는데 open 관련을 전부 expand로 바꾸는게 더 좋을 것 같아요 이미 열려있는 것이고 확장하는 개념이니까요 (게다가 기본적으로 연다는 행위와 중복되어 헷갈릴 수 있기에)

변수명 의미하시는 거죠 ?

2022-02-12 03:47 UTC, kynk94 commented
네 변수명 맞습니다 styled(drawer)에서도 내부가 그냥 expand 면 될것같아요
여는 행위에 대한 변수도 기본값으로 opened가 아니라 open을 쓰고 있으니까

2022-02-12 04:03 UTC, ecpark4545 commented
@kynk94 
수정요청 사항 반영하였습니다.
@hunhoon21 
자유인님. 리뷰 부탁드립니다. 👍

2022-02-12 04:04 UTC, hunhoon21 commented
> @kynk94 
> 
> 수정요청 사항 반영하였습니다.
> 
> @hunhoon21 
> 
> 자유인님. 리뷰 부탁드립니다. 👍

넹

2022-02-12 04:18 UTC, kynk94 requested changes

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/drawer.tsx
> +}, ({ expanded }: StyledDrawerProps)=> ({
과거분사 대신 현재형 expand 로 사용 가능한가요?

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/drawer.tsx
> +
비어있는 줄이 있네요

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/drawer.tsx
> +export default function CustomDrawer({ expanded } : StyledDrawerProps) {
CustomDrawer 대신 Drawer 그냥 사용해도 좋을 것 같아요
mui에서 가져오는것도 MuiDrawer니까 혼동될 일은 없어보입니다.

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/header.tsx
> +import React, { useState, useCallback } from 'react';
import 순서는 알파벳 순서입니다. { useCallback, useState } 순서가 되게 해주세요.
이 부분은 제가 eslint에 rule 추가해두겠습니다.

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  zIndex: '1400',
zIndex는 꼭 필요한 것인가요?

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  position: 'fixed',
default 값이 fixed이므로 추가할 필요 없습니다.

2022-02-12 04:18 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  const [expanded, setExpand] = useState(true);
const [expand, setExpand]

getter, setter의 이름을 통일시켜주세요

2022-02-12 04:21 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  position: 'fixed',
근데 이건 제가 업무로 frontend할 때 얘긴데요, 솔직히 저는 기본값이라도 명시하고 싶었는데 리뷰 받을 때 이런건 전부 제거하더라구요.
이유는 모르겠습니다.....

2022-02-12 04:24 UTC, ecpark4545 commented on frontend/src/components/drawer.tsx
> +}, ({ expanded }: StyledDrawerProps)=> ({
네, 그게 더 명확해보이네요 👍

2022-02-12 04:25 UTC, ecpark4545 commented on frontend/src/components/drawer.tsx
> +
제거하겠습니다

2022-02-12 04:25 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  zIndex: '1400',
zIndex는 웬만하면 사용하지 않는 것이 좋습니다.
지금 button에도 zIndex가 들어가있는데 해당부분 삭제예정입니다.

zIndex는 rendering하는 과정에서 component의 깊이를 설정하는 것입니다.
더 큰 값의 component가 위로 올라와서 다른 component를 덮어서 가리는 것이죠.
기본적으로 각각의 component가 설계된 값을 갖고 있고 그 값은 특별한 이유가 있지 않는 한 수정하지 않는 것이 좋습니다.

2022-02-12 04:25 UTC, ecpark4545 commented on frontend/src/components/drawer.tsx
> +export default function CustomDrawer({ expanded } : StyledDrawerProps) {
네 알겠습니다.

2022-02-12 04:27 UTC, ecpark4545 commented on frontend/src/components/header.tsx
> +import React, { useState, useCallback } from 'react';
네;;

2022-02-12 04:29 UTC, ecpark4545 commented on frontend/src/components/header.tsx
> +  position: 'fixed',
음... 저도 인구님과 같은 의견으로 명시한 부분인데요. 일단 제거하겠습니다.

2022-02-12 04:29 UTC, ecpark4545 commented on frontend/src/components/header.tsx
> +  const [expanded, setExpand] = useState(true);
기본적인 것을 놓쳤네요... 코멘트 감사합니다~

2022-02-12 04:36 UTC, ecpark4545 commented on frontend/src/components/header.tsx
> +  zIndex: '1400',
zIndex는 layout의 순서를 결정하는 config로 간단하게 이해하고 사용했던 기억이 있습니다.
다만, 1300, 1400, 1500 의 value를 지정해야 원하던 대로 작동을 하더라구요.
해당 부분은 theme 개념과 또 맞물려 있어서, 추가적인 공부를 한 뒤 제대로 설명드릴 수 있을 것 같습니다. 🙈
- zIndex에 대한 설명은 아래 링크와 같습니다.
- https://mui.com/customization/z-index/

2022-02-12 04:41 UTC, kynk94 commented on frontend/src/components/header.tsx
> +  zIndex: '1400',
아 mui에서 설정된 기본값이 appbar보다 drawer의 값이 더 높네요
Youtube는 appbar 아래에 drawer가 있는데 기본값대로면 제대로 동작하지 않겠군요

zIndex를 drawer값보다 높게 설정해야하네요
좋습니다!

2022-02-12 04:56 UTC, kynk94 approved these changes

2022-02-13 05:11 UTC, hunhoon21 commented on frontend/src/components/header.tsx
> +  }, [setExpand, expand]);
```suggestion
  const [isExpanded, setIsExpanded] = useState(true);

  const handleDrawer = useCallback(() => {
    setIsExpanded(!isExpanded);
  }, [setIsExpanded, isExpanded]);

```

isExpaned & setIsExpanded로 표현하는게 더 명확할것 같다는 생각입니다. 검색해봐도 많이 쓰는 표현인것 같습니다 ㅎ
![5A77D952-064B-49E5-A04C-C02F6CB1356E](https://user-images.githubusercontent.com/36983960/153739669-3a1ec991-6567-4282-98f5-f70ef2ee7e1e.png)

2022-02-13 05:13 UTC, hunhoon21 commented on frontend/src/components/header.tsx
> +    <Drawer expand={expand}/>
```suggestion
    <Drawer isExpanded={isExpanded}/>

```

2022-02-13 05:15 UTC, hunhoon21 commented on frontend/src/components/drawer.tsx
> +    <StyledDrawer variant="permanent" expand={expand}>
```suggestion
}, ({ isExpanded }: StyledDrawerProps)=> ({
  width: isExpanded ? 60 : 200,
  '& .MuiDrawer-paper': { width: isExpanded ? 60 : 200 },
}));

interface StyledDrawerProps {
  isExpanded : boolean,
}

export default function Drawer({ isExpanded } : StyledDrawerProps) {
  return (
    <StyledDrawer variant="permanent" isExpanded={isExpanded}>
```

2022-02-13 05:26 UTC, hunhoon21 commented on frontend/src/components/drawer.tsx
> +      {['홈', '탐색', '구독', 'originals'].map((text, index) => (
```suggestion
      {['Home', 'Exploration', 'Subscriptions', 'whatever'].map((text, index) => (
```

![81F90CFE-912D-4FE1-9569-0E2DBFB789BF](https://user-images.githubusercontent.com/36983960/153740063-b21920b2-2155-4f72-aef4-77b8950f1078.png)
물론 샘플로 임의로 넣어두신거겠지만 다른것으로 확장할 수 있다는 의미로 다른 문자들이 들어가 있으면 좋을 것 같습니다 ㅎㅎ

2022-02-13 05:29 UTC, hunhoon21 commented on frontend/src/components/header.tsx
> +  }, [setExpand, expand]);
styled 에서 대문자를 사용할 수 없어서 expand 로 해야한다는데 동의합니다.

2022-02-13 05:32 UTC, hunhoon21 commented on frontend/src/components/drawer.tsx
> +    <StyledDrawer variant="permanent" expand={expand}>
styled 에서 대문자를 사용할 수 없어서 expand 로 해야한다는데 동의합니다.
해당 conversation은 resolve 하도록 하겠습니다.

2022-02-13 05:45 UTC, hunhoon21 commented on frontend/src/components/header.tsx
> +    <Box>
해당부분의 가독성을 위해 indent를 맞춰주면 좋을 것 같습니다!
suggestion을 할 수는 없어서 바뀌어야될 내용으로 남겨둘게요.
```
    <Box>
      <StyledAppBar>
        <StyledToolbar variant="dense">
          <IconButton onClick={handleDrawer} size="large" edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
            <MenuIcon />
          </IconButton>
          <Box sx={{ flexGrow: 1 }}>
            <Typography variant="h6" component="div">
              Youtube
            </Typography>
          </Box>
          <SearchBox>
            <SearchInputBase placeholder="Search" />
            <Button variant="outlined" startIcon={<SearchIcon />} />
          </SearchBox>
          <AccountButton />
        </StyledToolbar>
      </StyledAppBar>
      <Drawer expand={isExpanded}/>
    </Box>
```

2022-02-13 05:46 UTC, hunhoon21 approved these changes
잘 작동하네요. 덕분에 drawer 구조 잘 살펴봤습니다 고생하셨습니다 👍

conversation으로 남겨둔 것들만 확인부탁드려요 ㅎㅎ

2022-02-13 12:56 UTC, kynk94 commented on frontend/src/components/header.tsx
>  import AccountButton from './account/account';
yarn lint 하면 잡히네요
pre-commit이 동작하지 않았나보네요
yarn lint 후 commit 부탁드려요

2022-02-20 09:46 UTC, merged

2022-02-20 09:46 UTC, ecpark4545 commented
@kynk94 @hunhoon21 
의견 반영해서 커밋 하였습니다.
이슈는 닫도록 하겠습니다.