✨ Yc-24 DB Table 설계
LLIHC/youtube-clone pull request #14
Opened 2022-01-30 07:02 UTC by hunhoon21

## Description

* Content 테이블 Model을 생성합니다.
* Channel 테이블 Model을 생성합니다.

2022-01-31 05:29 UTC, kynk94 requested changes

2022-01-31 05:29 UTC, kynk94 commented on backend/requirements.txt
> +uvicorn
uvicorn이 중복됩니다

2022-01-31 05:29 UTC, kynk94 commented on backend/src/models.py
> +    channel_followers = Column(Integer)
channel이라는 class 내부의 인자이므로 변수명에서 channel을 삭제하는 것이 좋아보입니다.

2022-01-31 05:29 UTC, kynk94 commented on backend/src/models.py
> +    content_thumbnail_url = Column(String)
위와 동일하게 content는 빠지는 것이 좋아보입니다.

2022-02-05 17:20 UTC, hunhoon21 commented on backend/requirements.txt
> +uvicorn
```suggestion

```

2022-02-05 17:21 UTC, hunhoon21 commented on backend/src/models.py
> +    channel_followers = Column(Integer)
```suggestion
    thumbnail_url = Column(String, index=True)
    name = Column(String)
    followers = Column(Integer)
```

2022-02-05 17:22 UTC, hunhoon21 commented on backend/src/models.py
> +    content_thumbnail_url = Column(String)
```suggestion
    thumbnail_url = Column(String)
```

2022-02-05 17:22 UTC, hunhoon21 commented on backend/requirements.txt
> +uvicorn
삭제했습니다.

2022-02-05 17:22 UTC, hunhoon21 commented on backend/src/models.py
> +    channel_followers = Column(Integer)
제거했습니다!

2022-02-05 17:22 UTC, hunhoon21 commented on backend/src/models.py
> +    content_thumbnail_url = Column(String)
제거했습니다~

2022-02-13 13:39 UTC, hunhoon21 commented on backend/src/app/schemas.py
> +    n_followers: int
```suggestion
    # n_followers: int
```

2022-02-13 13:44 UTC, hunhoon21 commented
@kynk94 리뷰 가능 상태로 바꿔두었습니다-!

2022-02-14 01:06 UTC, kynk94 requested changes
고생하셨습니다.

이건 그냥 질문 드리는 건데,
models는 db의 table의 형태이고
schemas는 db에 전송할 request의 형태인거죠?

2022-02-14 01:06 UTC, kynk94 commented on backend/src/app/models.py
> +    content_description = Column(String)
변수명에 content가 남아있습니다

2022-02-14 01:06 UTC, kynk94 commented on backend/src/app/schemas.py
> +    content_description: str
위와 마찬가지입니다.

2022-02-14 09:38 UTC, hunhoon21 commented
> 이건 그냥 질문 드리는 건데,
> models는 db의 table의 형태이고
> schemas는 db에 전송할 request의 형태인거죠?

넵 맞습니다-!
API에서 주고받을때 schemas 에서 정의한 데이터모델을 활용하고, 실제 DB 객체를 만들때 models 에서 정의한 데이터모델을 활용합니다

2022-02-14 09:42 UTC, hunhoon21 commented on backend/src/app/schemas.py
> +    content_description: str
반영했슴다!

2022-02-14 13:39 UTC, kynk94 approved these changes

2022-02-22 14:57 UTC, hunhoon21 commented
@JunnGT 리뷰 부탁드립니다-!

2022-02-27 19:44 UTC, JunnGT reviewed
몇 가지 리뷰하였습니다!

2022-03-06 04:12 UTC, hunhoon21 commented on backend/src/app/schemas.py
> +    pass
앗 리뷰온지 몰랐네요!

2022-03-06 04:13 UTC, hunhoon21 commented on backend/src/app/schemas.py
> +    pass
네, 컨텐츠를 만드는 Post 시에 사용하는 데이터모델입니다!

2022-03-06 04:29 UTC, hunhoon21 commented on backend/src/app/schemas.py
> +        orm_mode = True
ContentBase, Content, ContentCreate 각각 목적이 있으므로 현재에서 굳이 나누지 않아도 될 것 같다는 의견입니다-

2022-03-06 04:30 UTC, JunnGT approved these changes
답변 감사합니다! 궁긍즘 해결되었습니다:)

2022-03-06 04:31 UTC, merged