WIP: 👷 ✨ Yc-10 simple READ Contents
LLIHC/youtube-clone pull request #15
Opened 2022-01-30 07:25 UTC by hunhoon21

## description
* contents 를 읽어들이는 간단한 READ를 구현합니다.

2022-02-02 06:11 UTC, kynk94 requested changes

2022-02-02 06:11 UTC, kynk94 commented on backend/src/main.py
> +
main에서는 이러한 작업을 피해주세요.

get_db는 #14 에서 `backend/src/database.py` 하단에 옮겨주세요.

read_contents에서 response_model은 무엇인가요?
str도 아닌데 import나 정의가 되어있지 않아 궁금하네요.

그리고 아래와 같이 코드를 옮겨주세요
```python
# app/endpoints/contents.py
from fastapi import APIRouter

router = APIRouter()


@router.get("/contents/", response_model)
def read_contents(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    contents = crud.get_contents(db, skip=skip, limit=limit)
    return contents
```

```python
# app/api.py 
from fastapi import APIRouter
from app.endpoints import contents

api_router = APIRouter()
api_router.include_router(contents.router, prefix="/contents", tags=["contents"])
```

2022-02-02 06:21 UTC, kynk94 commented on backend/src/main.py
> +
그런데 뭔가 reviewer에 제가 등록돼 있어서 리뷰를 남겼는데, 아직 리뷰단계가 아닌 상태였죠 아마...?

2022-02-02 09:17 UTC, hunhoon21 commented on backend/src/main.py
> +
리뷰는 항상 감사합니다!

2022-02-13 13:44 UTC, hunhoon21 commented
@kynk94 리뷰 가능 상태로 바꿔두었습니다-!

2022-02-14 01:10 UTC, kynk94 requested changes
앞선 리뷰에서 main.py에서 내용을 분리해달라는 부분만 맞춰주시면 될 것 같습니다

2022-02-14 01:10 UTC, kynk94 commented on backend/src/app/crud.py
> +from . import models, schemas
No parent module -- cannot perform relative import

mypy가 통과하지 않습니다.

2022-02-14 09:56 UTC, hunhoon21 commented on backend/src/app/crud.py
> +from . import models, schemas
잠시만여 마이파이는 다시 볼게여 일단 구조는 수정했어요

2022-02-22 13:06 UTC, kynk94 commented
mypy 오류 수정되면 언급해주세요~

2022-02-22 14:52 UTC, hunhoon21 commented on backend/src/app/crud.py
> +from . import models, schemas
현재 제쪽에서 해당 에러가 발생하지 않는데 다시 마이파이 체크해봐도 이 에러가 나나요?

2022-02-22 14:56 UTC, hunhoon21 commented on backend/src/app/crud.py
> +from . import models, schemas
일단 type: ignore은 안할게요. 저는 같은 에러가 안발생해서 에러 발생 재현먼저 하면 좋을것 같습니다!

2022-02-22 15:27 UTC, kynk94 commented on backend/src/app/crud.py
> +from . import models, schemas
__init__.py 추가한 커밋 이후로는 잘 통과되네요!
resolve 하겠습니다

2022-02-22 15:27 UTC, kynk94 approved these changes

2022-02-27 19:17 UTC, JunnGT approved these changes

2022-03-06 04:47 UTC, merged