Yc 31 로그인 시 계정 아바타 DropDown 메뉴 적용
LLIHC/youtube-clone pull request #18
Opened 2022-02-10 13:46 UTC by LEEMINJOO

YC-18 에서 작업한 Branch로, YC-18이 머지되면 object branch 를 develop으로 변경하겠습니다.

https://user-images.githubusercontent.com/42792260/153420562-3ee1cdfb-cfd2-492a-ac87-cc8d2545c443.mov

2022-02-12 08:21 UTC, ecpark4545 reviewed
@LEEMINJOO @kynk94 
커멘트 달았습니다.
인구님 추가 커멘트 보고 
저도 다시 확인한 후 approve 하도록 하겠습니다.

2022-02-12 08:21 UTC, ecpark4545 commented on frontend/src/components/account/avatar.tsx
> +export default function AvatarButton(props: any) {
이 부분 props type도 지정가능하지 않나요?

2022-02-12 08:21 UTC, ecpark4545 commented on frontend/src/components/account/avatarMenu.tsx
> +import React, { useState, useCallback } from 'react';
useCallback ->  useState  이 순서로 import하는게 맞을거 같아요!

2022-02-12 08:21 UTC, ecpark4545 commented on frontend/src/components/account/avatarMenu.tsx
> +  }, [setAnchorEl]);
`handleClose`도 click event를 input으로 받지 않나요 ?
만약 그렇다면, 명시하는게 나을거 같긴한데... 그렇더라도 또 쓰이진 않네요..
이 부분은 다른분의 의견도 들어보고 싶네요.

@kynk94 @hunhoon21

2022-02-12 09:35 UTC, kynk94 requested changes

2022-02-12 09:35 UTC, kynk94 commented on frontend/src/components/account/avatarMenu.tsx
> +  const handleClick = useCallback((event: any) => {
event: React.MouseEvent\<HTMLInputElement\>
anchorElement의 useState type도 호환되게 수정하시면 될 것 같습니다.

2022-02-12 09:35 UTC, kynk94 commented on frontend/src/components/account/avatarMenu.tsx
> +  }, [setAnchorEl]);
사용하지 않는 click event를 받을 수 있는 것이지, 받아야만 하는 것은 아니기 때문에 비워두는게 나아보입니다.

2022-02-12 09:35 UTC, kynk94 commented on frontend/src/components/account/avatar.tsx
> +export default function AvatarButton(props: any) {
props는 반드시 AvatarButton({ one, another, other }: Props)으로 펼쳐주세요

interface Props도 바로 위에 작성해주시면 될 것 같습니다.

2022-02-12 09:35 UTC, kynk94 commented on frontend/src/components/account/avatar.tsx
> +const StyledImg = styled('img')((props: any) => ({
별도의 새로운 prop이 아니라 HTMLImageElement가 기본으로 갖고 있는 prop이기 때문에 괜찮습니다.
```suggestion
const StyledImg = styled('img')((open) => ({
```

2022-02-12 09:35 UTC, kynk94 commented on frontend/src/components/account/avatar.tsx
> +const StyledImg = styled('img')((props: any) => ({
명시할 수 있다면 명시해주시면 좋은데, img의 prop type을 구글링 중인데 찾기가 쉽지 않네요

2022-02-12 10:12 UTC, LEEMINJOO commented on frontend/src/components/account/avatar.tsx
> +export default function AvatarButton(props: any) {
@ecpark4545 @kynk94 
AvatarButton 아래 StyledButton이 있어 AvatarButton에서 받은 Prop를 모두 StyledButton에 넘겨줍니다.
StyledButton은 Button의 Wrapping이고요.

이때는 Button에서 받을 수 있는 모든 Props를 Interface로 정의해 줘야하는건가요?
아니면 이중에서 사용하는 일부 Props만 갖느 Interface를 정의해줘야하나요? 

StyledImg에서도 같은 맥락으로 any를 받았습니다.

2022-02-12 11:07 UTC, kynk94 commented on frontend/src/components/account/avatar.tsx
> +const StyledImg = styled('img')((props: any) => ({
```suggestion

interface IStyledImgProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  open: boolean;
}

const StyledImg = styled('img')(({open}: IStyledImgProps) => ({
  height: '32px',
  width: '32px',
  borderRadius: '70%',
  border: open ? '0px' : '1px solid blue',
}));
```

이렇게 수정하시면 되는것 같네요

2022-02-12 13:04 UTC, kynk94 commented on frontend/src/components/google-login.tsx
> +  const onSuccess = async (response: any) => {
```suggestion
import { GoogleLoginResponse } from 'react-google-login'

const onSuccess = async (response: GoogleLoginResponse) => {
```

2022-02-12 13:45 UTC, kynk94 requested changes

2022-02-12 13:45 UTC, kynk94 commented on frontend/src/components/account/avatar.tsx
> +const StyledImg = styled('img')((props: any) => ({
또 이름을 StyledImg 대신 AvatarImg 로 쓰시면 훨씬 명확해 보이네요.

Appbar, Header, Drawer 등 특별히 이름 붙이기 어려운 경우에 StyledAppbar 등으로 사용하고 그 외에 이름을 붙일 요건이 있다면 훨씬 좋은 코드가 되는 것 같아요

2022-02-19 12:07 UTC, LEEMINJOO commented on frontend/src/components/google-login.tsx
> +  const onSuccess = async (response: any) => {
타입명시 했습니다

2022-02-19 12:08 UTC, LEEMINJOO commented on frontend/src/components/account/avatar.tsx
> +const StyledImg = styled('img')((props: any) => ({
suggestion 감사합니다 ! 덕분에 쉽게 변경했습니다
컴포넌트 명도 AvatarImg로 변경했습니다

2022-02-19 12:09 UTC, LEEMINJOO commented on frontend/src/components/account/avatar.tsx
> +export default function AvatarButton(props: any) {
@kynk94 도음 감사합니다 적용했습니다

2022-02-19 12:10 UTC, LEEMINJOO commented on frontend/src/components/account/avatarMenu.tsx
> +  const handleClick = useCallback((event: any) => {
넵 적용했습니다

2022-02-19 12:20 UTC, kynk94 approved these changes

2022-02-19 12:21 UTC, kynk94 commented
고생많으셨습니다!
마지막 commit의 El은 공식적으로도 많이 써서 El로 써도 괜찮습니다 ㅎㅎ
Element로 쓰는게 더 좋은 것은 명확합니다.

2022-02-20 09:55 UTC, ecpark4545 approved these changes

2022-03-05 13:18 UTC, merged