:hammer: initialize DB & add a root channel
LLIHC/youtube-clone pull request #22
Opened 2022-02-26 15:40 UTC by hunhoon21

### Description
DB 초기화 후 root user를 추가합니다.

(이제 항상 들어있음)
![4CD9F906-253A-4461-8FFE-B5B52BC16039](https://user-images.githubusercontent.com/36983960/155849192-4af20433-2178-45a6-b711-7c2a8afc7a97.png)

2022-02-27 09:18 UTC, kynk94 requested changes

2022-02-27 09:18 UTC, kynk94 commented on backend/src/app/init_database.py
> +from . import models
이 파일의 내용인 `initialize_db` function을 `backend/src/app/database.py` 내부로 옮기면 좋아보입니다.
또한 import 하여 사용하는 것이 아니라 database.py 내부에서 initialize_db() 으로 바로 call 하는 것으로 다른 곳에서 관리할 필요가 없다고 생각됩니다.

2022-02-27 09:18 UTC, kynk94 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
여기서 models에 binding 하는 부분도 database.py 내부에서 이뤄져도 문제가 없어보입니다.
main에서 굳이 binding하지 않아도, 
### 어차피 database를 사용하는 시점에 models에는 당연히 bind가 되어있어야만 합니다.
그러므로 database.py 안에서 bind가 일어난다면 직관적으로 보입니다.

2022-02-27 09:30 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
이게 시점상 되는지 모르겠는데요, Base를 기반으로 만든 models 내부 클래스들(각 테이블)이 만들어지고 나서 binding이 이뤄져야 하는것으로 보입니다. database.py 내부에서 바인딩하면 models 내부 클래스들을 engine에 바인딩하기 쉽지 않아보이는데요.

2022-02-27 09:31 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
일단 잠시만요 서큘러 임포트가 떠서 해결해볼게요

2022-02-27 09:35 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
말씀대로 database.py 내부에서 bind 되는게 좋아보입니다

2022-02-27 09:42 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
> 이게 시점상 되는지 모르겠는데요, Base를 기반으로 만든 models 내부 클래스들(각 테이블)이 만들어지고 나서 binding이 이뤄져야 하는것으로 보입니다

이거 혹시 설명 가능한사람 있나?ㅋㅋ 안될거같은데 잘 되네

2022-02-27 09:45 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
7acce7f 에서 반영했습니다

2022-02-27 09:54 UTC, hunhoon21 commented on backend/src/app/init_database.py
> +from . import models
[90ef25c](https://github.com/LLIHC/youtube-clone/pull/22/commits/90ef25cb95b1d8e47176ba62358002a35cde8fa2) 에서 반영했습니다. 
데이터베이스를 초기화 하는 함수는 database.py 내부로 옮겼는데요. 해당 파일에서 실행하면 이미 channels.hashed_id 가 값이 존재하여 UNIQUE 제한 룰에 위배된다며 에러가 발생합니다. 분명 INSERT 하기 전에 테이블을 초기화하는 로직을 추가하였으니 괜찮아야 할 것 같은데 어떤 시점에서 문제가 발생하는건지 잘 모르겠네요;

에러메시지는 다음과 같습니다.

```
Process SpawnProcess-19:
Traceback (most recent call last):
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: channels.hashed_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/uvicorn/server.py", line 74, in serve
    config.load()
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/henris/workspace/youtube-clone/backend/src/./main.py", line 6, in <module>
    from app.api import api_router
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/api.py", line 3, in <module>
    from app.endpoints import channels
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/endpoints/channels.py", line 6, in <module>
    from .. import crud, database, schemas
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/crud.py", line 3, in <module>
    from . import models, schemas
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/models.py", line 4, in <module>
    from .database import Base, engine
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/database.py", line 39, in <module>
    initialize_db()
  File "/Users/henris/workspace/youtube-clone/backend/src/./app/database.py", line 24, in initialize_db
    conn.execute(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1274, in execute
    return self._exec_driver_sql(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/henris/miniconda3/envs/youtube/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: channels.hashed_id
[SQL: 
            INSERT INTO channels(hashed_id, thumbnail_url, name)
            VALUES ('faked_id', 'google.com', 'root')
        ]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

2022-02-27 09:55 UTC, hunhoon21 commented on backend/src/app/init_database.py
> +from . import models
일단 초기화하는 것은 `main.py` 에서 실행하는 것으로 하면 문제가 없어서 해당 방향으록 구현해두었습니다.
(또한 저는 바인딩 등 데이터베이스 설정은 완료된 후에 본 main.py의 역할을 수행하면서 데이터베이스를 초기화하는 것도 괜찮아보이기는 합니다)

2022-02-27 09:56 UTC, hunhoon21 commented
@kynk94 코멘트에 답 달아두었습니다-!

2022-02-27 10:39 UTC, kynk94 commented on backend/src/app/init_database.py
> +from . import models
확실히 에러가 까다로워보이네요
main에서 해당 함수 call하는 것은 저도 괜찮아보입니다.

2022-02-27 10:43 UTC, hunhoon21 commented on backend/src/app/init_database.py
> +from . import models
넵 리졸브 부탁드려용!

2022-02-27 10:45 UTC, kynk94 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
앞선 PR이 merge가 되지 않아 살펴보기가 힘들긴 하네요

보니까 models.Base 가 database.Base로 정의된것을 import 해 온 것이네요

database.Base로 정의된 후, database 내부에서 bind가 되었고 Bind 된 이후 models에서 상속한 테이블이 선언된 것인데 에러가 나지 않는 것으로 저는 2가지 이유를 추측합니다.
1. 같은 memory주소를 공유하기 때문에 에러가 일어나지 않는 것으로 추측
2. database에서 Base 선언 -> model에서 database.Base import -> model.py 내부 선언 완료 -> database에서 model.Base import. 즉, compile 순서에 따라 오류가 일어나지 않았던 것으로 추측

2번이 좀 더 그럴듯해 보이는데 내부에 잘 bind가 된 것인지 확인하는 test코드가 필요해 보입니다.

2022-02-27 10:53 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
저는 같은 메모리 공유해서 괜찮지 않을까 싶었긴했는데 bind부터 다시 한번 살펴볼게요

2022-02-27 11:02 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
* binding 전후 로깅
![A5CECF8E-1B30-4908-96F8-3E2C03BD7976](https://user-images.githubusercontent.com/36983960/155879745-a4bbe292-8b35-4e95-a22d-29ce2a61f35c.png)

* models.py 로깅
![9DDBE891-940D-46A4-A5F3-93698D8D4640](https://user-images.githubusercontent.com/36983960/155879764-1d5d57e8-1cf8-4b17-b28f-9b013c898f5a.png)

* 로깅 결과
![FB2AB377-BECF-40AD-8310-1702956F29E7](https://user-images.githubusercontent.com/36983960/155879784-0fae12d4-2b8b-41af-896a-b912a6a192a7.png)

2022-02-27 11:33 UTC, kynk94 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
하나의 dict를 공유해서 같은 메모리를 갖기에 문제 없는게 맞아 보이네요

2022-02-27 11:34 UTC, kynk94 approved these changes

2022-02-27 11:40 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
테이블을 생성하는 시점은 create_all 을 하는 시점이 맞아 해당 소스코드에 문제가 있었던게 맞는 것 같습니다. 기존에 에러가 안났던건.. db 파일이 로컬에 남아있었어서 괜찮았던것 같아요..ㅎㅎ;


그래서 제대로 테이블을 생성하려면 models.py 가 읽혀진 이후에 해야합니다.
일단은 models.py 내부에서 테이블을 생성하게 했고, 아무런 db 파일이 없을때도 문제없이 잘 작동하네요.

좀더 개선의 여지는 있어보입니다만은 현재 로직상 문제는 없어보입니다

2022-02-27 11:41 UTC, hunhoon21 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
[fd8e812](https://github.com/LLIHC/youtube-clone/pull/22/commits/fd8e8128161c5e4959572faf5fb6d256fe190c09)

@kynk94 코멘트 추가로 남긴게 있는데 확인 부탁드려용!

2022-02-27 11:42 UTC, kynk94 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
확인하였습니다! 고생하셨습니다~
이후 model이 여러종류가 되고 복잡해질 경우 다시 논의가 필요하겠네요

2022-03-06 04:52 UTC, hunhoon21 commented
@ecpark4545 채도 리뷰좀!

2022-03-06 07:50 UTC, ecpark4545 commented on backend/src/main.py
>  models.Base.metadata.create_all(bind=engine)
@hunhoon21 @kynk94 
두 분 코멘트 모두 확인하였습니다. 👍

위에서 논의한 바인딩 시점 괸련해서 `파이썬 임포트 타임` 이라는 키워드로 서치를 해봤는데요. (이해에 도움이 되실까 적어봅니다!)

> 인터프리터는 임포트 타임에 클래스 안에 들어 있는 클래스의 `본체`까지 모든 클래스의 `본체`를 실행한다.
> 클래스 본체를 실행한다는 것은 클래스의 속성과 메서드가 정의되고, 클래스 객체가 만들어짐을 의미한다.
> 이런 관점에서 보면 클래스 본체는 `최상위 수준 코드`다.
> 임포트 타임에 실행되기 때문이다.
> (전문가를 위한 파이썬 chap 21.3 임포트 타임과 런타임)

2022-03-06 07:50 UTC, ecpark4545 approved these changes
@hunhoon21 
고생하셨습니다 👍

2022-03-06 07:57 UTC, merged

2022-03-06 09:50 UTC, LEEMINJOO commented on backend/src/main.py
> +initialize_db()
@hunhoon21 db 초기화를 `if __name__ == "__main__":` (스크립트 실행시)가 아닌 전역 변수 식으로 해주는 이유가 궁금합니다.(몰라서 물어보는 거에요!)